ENV["RACK_ENV"] = 'test'
require './app/quiz_app'
require 'capybara/rspec'
require 'database_cleaner'
require 'selenium-webdriver'
require './spec/helpers/admin_helpers'
require 'factory_girl'
require 'capybara/poltergeist'

Dir[File.expand_path(File.join(File.dirname(__FILE__),'support','**','*.rb'))].each {|f| require f}


FactoryGirl.definition_file_paths = %w{./factories ./test/factories ./spec/factories}
FactoryGirl.find_definitions
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

Capybara.app = QuizApp
Capybara.javascript_driver = :poltergeist

RSpec.configure do |config|

  # config.order = 'random'
  config.order = 'default'
  config.include AdminHelpers

  config.before :suite do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with :truncation
    Capybara.javascript_driver = :poltergeist
  end

  config.before :each do
    if example.metadata[:js]
      DatabaseCleaner.strategy = :truncation
    else
      DatabaseCleaner.strategy = :transaction
      DatabaseCleaner.start
    end
  end

  config.after :each do
    DatabaseCleaner.clean
  end

end